### ISSUE TITLE
Fix "connectionType" and "dataSource" information

### ISSUE THREAD

**Issue by klein0r** [schmupu/ioBroker.pollenflug#29]
Should be

```
"connectionType": "cloud",
"dataSource": "poll",
```

instead of

https://github.com/schmupu/ioBroker.pollenflug/blob/4ae37990c9c6bcf9ae5db5bfa0c9fba70b005e7f/io-package.json#L173-L174

Documentation: https://github.com/ioBroker/ioBroker.repositories/blob/master/README.md#connection-types

**Comment by mcm1957** [comment]
fixed with upcoming 2.0.0

----------

This adapter has been transferred into iobroker-community-adapters organisation.
The new repository can be found here: https://github.com/iobroker-community-adapters/ioBroker.pollenflug

**Please note that this issue will no longer be processed.**
Please test the migrated version (2.0.0) as soon as it will be available at latest repository and create a new issue at https://github.com/iobroker-community-adapters/ioBroker.pollenflug/issues if any problem still exists.
