### ISSUE TITLE
showing wrong date

### ISSUE THREAD

**Issue by lobomau76** [schmupu/ioBroker.pollenflug#31]
I am using Version 1.0.6.

Today is 14.12.2021, Tuesday.
Only "dayaftertomorrow" shows right:
Edit: "dayaftertomorrow" shows wrong, too. But the probems has been solved. The service from DWD was the problem.

![image](https://user-images.githubusercontent.com/35029301/145988627-cc514681-0941-4658-9719-b848e46998d9.png)

**Comment by RelaxedHome** [comment]
I'm using Version 1.0.6
I'm not sure if this mistake has something to do with it. The error has existed since today.


2021-12-14 15:18:38.549 | error | Error reading pollen risk index.


2021-12-14 15:18:38.548 | error | Error requesting URL https://opendata.dwd.de/climate_environment/health/alerts/s31fg.json (StatusCodeError: 404 - "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n")
-- | -- | --

**Comment by Milbert-R** [comment]
same here

`<html>
<body>


pollenflug.0 | 2021-12-15 13:11:23.693 | error | Error reading pollen risk index.
-- | -- | -- | --
pollenflug.0 | 2021-12-15 13:11:23.692 | error | Error requesting URL https://opendata.dwd.de/climate_environment/health/alerts/s31fg.json (StatusCodeError: 404 - "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n")


</body>
</html>`

**Comment by lobomau76** [comment]
Problem was not the Adapter, it was the DWD site.
